# set server port
server:
  port: 8090  # 配置端口
spring:
  datasource: # set database config
    url: jdbc:mysql://47.98.189.101:3306/itools?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234=Qwer
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  http:
    converters:
      preferred-json-mapper: fastjson       # Json转换器

  devtools:
    livereload:
      enabled : true
############################## mybatis-plus配置 开始  ##############################
mybatis-plus:
  mapper-locations: classpath*:com/**/mapper/*.xml
  type-aliases-package: com.xxxx.**.entity
  type-handlers-package: com.example.springbootdemo.typeHandler
  type-enums-package: com.miaoc.itools.enums #com.jxdinfo.hussar.common.constant.enums
  global-config:
    id-type: 3                                              # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    db-column-underline: false                               #驼峰下划线转换

  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true                                     # 配置的缓存的全局开关
    lazyLoadingEnabled: true                                # 延时加载的开关
    multipleResultSetsEnabled: true                         # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印sql语句,调试用

    ############################## mybatis-plus配置 结束  ##############################

message:
  accesskeyid: accesskeyid
  accesssecret: accesssecret
  signname: 微快递
  templatecode: SMS_138077924
